# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 13306:3306
    volumes:
      - ./.mysql:/docker-entrypoint-initdb.d
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]

  service:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DATABASE_URL=mysql://root:test@db:3306/WegatherBackendService
    command:
      [
        'dockerize',
        '-wait',
        'tcp://db:3306',
        '-timeout',
        '2m',
        'yarn',
        'start:dev',
      ]
    ports:
      - '4000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
